routes:
  /:
    template: home
  /blog/:
    template: blog
  /newsletter/:
    template: newsletter  
  /start/:
    template: start
  /all-articles/:
    template: all-articles
  /all-tags/:
    template: all-tags
collections:
  /:
    permalink: /{slug}/
    template: index
  /blog/:
    permalink: /blog/{slug}/
    template: index
    filter: primary_tag:blog
  /newsletter/:
    permalink: /newsletter/{slug}/
    template: index
    filter: primary_tag:newsletter
taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
