routes:
  /:
    template: home
  /blog/:
    template: blog
  /start/:
    template: start
collections:
  /:
    permalink: /{slug}/
    template: index
  /blog/:
    permalink: /blog/{slug}/
    template: index
    filter: primary_tag:blog
  /newsletter/:
    permalink: /newsletter/{slug}/
    template: index
    filter: primary_tag:newletter
taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
